import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/navigation'
import { FilterProvider } from '../contexts'
import styles from '../styles/Home.module.css'

/**
 *
 *
 * navigation
 * - filter
 *
 * locals
 * - local
 *
 *
 */

const Home: NextPage = () => {
  const filters = ['English', 'Espaniol', 'Italiano', 'Nederlands']

  return (
    <FilterProvider filters={filters}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navigation />
      </div>
    </FilterProvider>
  )
}

export default Home
